// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgpoyuabcvemmihlsipg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRncG95dWFiY3ZlbW1paGxzaXBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5NDg4NTksImV4cCI6MjA1NDUyNDg1OX0.PEbN29n5SC2_8QfqBXbxePp9ZAi-cfwikUlF51YRti8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);